.PHONY: default clean

default:
	make -C feynman-hibbs
	make -C fitzpatrick
	make -C jordan
	make -C lancaster-blundell
	make -C miller
	make -C susskind-friedman

clean:
	make -C feynman-hibbs clean
	make -C fitzpatrick clean
	make -C jordan clean
	make -C lancaster-blundell clean
	make -C miller clean
	make -C susskind-friedman clean

